In [1]:
# Importing the necessary package 
import yfinance

In [3]:
# Ignoring warning messages
import warnings 
warnings.filterwarnings("ignore")

In [9]:
# Using the .download() method to get our data

raw_data = yfinance.download (
    tickers = "^GSPC ^FTSE ^N225 ^GDAXI",
    start = "1994-01-07",
    end = "2019-09-27",
    interval = "1d",
    group_by = 'ticker',
    auto_adjust = True,
    threads = True)

# tickers -> The time series we are interested in - (in our case, these are the S&P, FTSE, NIKKEI and DAX)
# start -> The starting date of our data set
# end -> The ending date of our data set (at the time of upload, this is the current date)
# interval -> The distance in time between two recorded observations. Since we're using daily closing prices, we set it equal to "1d", which indicates 1 day. 
# group_by -> The way we want to group the scraped data. Usually we want it to be "ticker", so that we have all the information about a time series in 1 variable.
# auto_adjust -> Automatically adjust the closing prices for each period. 
# treads - > Whether to use threads for mass downloading.

raw_data

[*********************100%***********************]  4 of 4 completed

Ticker            ^GDAXI                                            \
Price               Open          High           Low         Close
Date
1994-01-07   2218.959961   2227.639893   2201.820068   2224.949951
1994-01-10   2231.840088   2238.010010   2222.000000   2225.000000
1994-01-11   2225.429932   2235.610107   2225.179932   2228.100098
1994-01-12   2227.120117   2227.790039   2182.060059   2182.060059
1994-01-13   2171.500000   2183.709961   2134.100098   2142.370117
...                  ...           ...           ...           ...
2019-09-20  12462.570312  12490.839844  12418.500000  12468.009766
2019-09-23  12432.299805  12441.019531  12264.139648  12342.330078
2019-09-24  12368.959961  12375.309570  12307.150391  12307.150391
2019-09-25  12250.080078  12261.059570  12141.820312  12234.179688
2019-09-26  12227.769531  12313.150391  12223.290039  12288.540039

Ticker                         ^GSPC                                         \
Price            Volume         Open         High          Low        Close
Date
1994-01-07          0.0   467.089996   470.260010   467.029999   469.899994
1994-01-10          0.0   469.899994   475.269989   469.549988   475.269989
1994-01-11          0.0   475.269989   475.279999   473.269989   474.130005
1994-01-12          0.0   474.130005   475.059998   472.140015   474.170013
1994-01-13          0.0   474.170013   474.170013   471.799988   472.470001
...                 ...          ...          ...          ...          ...
2019-09-20  192994000.0  3008.419922  3016.370117  2984.679932  2992.070068
2019-09-23   80383600.0  2983.500000  2999.149902  2982.229980  2991.780029
2019-09-24   60350800.0  3002.429932  3007.979980  2957.729980  2966.600098
2019-09-25   72631600.0  2968.350098  2989.820068  2952.860107  2984.870117
2019-09-26   78923300.0  2985.729980  2987.280029  2963.709961  2977.620117

Ticker                           ^N225                              \
Price             Volume          Open          High           Low
Date
1994-01-07  3.249200e+08  17842.980469  18131.410156  17787.480469
1994-01-10  3.194900e+08  18186.519531  18567.060547  18186.519531
1994-01-11  3.054900e+08  18481.849609  18671.669922  18373.039062
1994-01-12  3.106900e+08  18447.339844  18807.080078  18301.929688
1994-01-13  2.779700e+08  18770.380859  18823.380859  18548.750000
...                  ...           ...           ...           ...
2019-09-20  6.103440e+09  22130.740234  22204.750000  22047.900391
2019-09-23  3.187250e+09           NaN           NaN           NaN
2019-09-24  3.872800e+09  22095.349609  22168.740234  22077.939453
2019-09-25  3.331200e+09  21961.820312  22036.480469  21906.000000
2019-09-26  3.084910e+09  22160.519531  22184.910156  21986.240234

Ticker                                      ^FTSE                            \
Price              Close      Volume         Open         High          Low
Date
1994-01-07  18124.009766         0.0  3401.399902  3446.800049  3398.699951
1994-01-10  18443.439453         0.0  3465.699951  3468.100098  3430.000000
1994-01-11  18485.250000         0.0  3442.500000  3442.500000  3413.500000
1994-01-12  18793.880859         0.0  3394.800049  3402.399902  3372.000000
1994-01-13  18577.259766         0.0  3380.699951  3383.300049  3356.899902
...                  ...         ...          ...          ...          ...
2019-09-20  22079.089844  85000000.0  7356.399902  7376.299805  7322.000000
2019-09-23           NaN         NaN  7344.899902  7362.299805  7284.799805
2019-09-24  22098.839844  68400000.0  7326.100098  7349.000000  7281.899902
2019-09-25  22020.150391  61600000.0  7291.399902  7292.000000  7213.000000
2019-09-26  22048.240234  81600000.0  7290.000000  7387.100098  7277.200195

Ticker
Price             Close        Volume
Date
1994-01-07  3446.000000  0.000000e+00
1994-01-10  3440.600098  0.000000e+00
1994-01-11  3413.800049  0.000000e+00
1994-01-12  3372.000000  0.000000e+00
1994-01-13  3360.000000  0.000000e+00
...                 ...           ...
2019-09-20  7344.899902  1.656288e+09
2019-09-23  7326.100098  4.896603e+08
2019-09-24  7291.399902  5.887722e+08
2019-09-25  7290.000000  7.045531e+08
2019-09-26  7351.100098  7.047075e+08

[6692 rows x 20 columns]

In [10]:
# Creating a back up copy in case we remove/alter elements of the data by mistake
df_comp = raw_data.copy()

In [11]:
# Adding new columns to the data set
df_comp['spx'] = df_comp['^GSPC'].Close
df_comp['dax'] = df_comp['^GDAXI'].Close
df_comp['ftse'] = df_comp['^FTSE'].Close
df_comp['nikkei'] = df_comp['^N225'].Close
df_comp.head()

Ticker           ^GDAXI                                                \
Price              Open         High          Low        Close Volume
Date
1994-01-07  2218.959961  2227.639893  2201.820068  2224.949951    0.0
1994-01-10  2231.840088  2238.010010  2222.000000  2225.000000    0.0
1994-01-11  2225.429932  2235.610107  2225.179932  2228.100098    0.0
1994-01-12  2227.120117  2227.790039  2182.060059  2182.060059    0.0
1994-01-13  2171.500000  2183.709961  2134.100098  2142.370117    0.0

Ticker           ^GSPC                                                   ...  \
Price             Open        High         Low       Close       Volume  ...
Date                                                                     ...
1994-01-07  467.089996  470.260010  467.029999  469.899994  324920000.0  ...
1994-01-10  469.899994  475.269989  469.549988  475.269989  319490000.0  ...
1994-01-11  475.269989  475.279999  473.269989  474.130005  305490000.0  ...
1994-01-12  474.130005  475.059998  472.140015  474.170013  310690000.0  ...
1994-01-13  474.170013  474.170013  471.799988  472.470001  277970000.0  ...

Ticker      ^N225        ^FTSE                                                \
Price      Volume         Open         High          Low        Close Volume
Date
1994-01-07    0.0  3401.399902  3446.800049  3398.699951  3446.000000    0.0
1994-01-10    0.0  3465.699951  3468.100098  3430.000000  3440.600098    0.0
1994-01-11    0.0  3442.500000  3442.500000  3413.500000  3413.800049    0.0
1994-01-12    0.0  3394.800049  3402.399902  3372.000000  3372.000000    0.0
1994-01-13    0.0  3380.699951  3383.300049  3356.899902  3360.000000    0.0

Ticker             spx          dax         ftse        nikkei
Price
Date
1994-01-07  469.899994  2224.949951  3446.000000  18124.009766
1994-01-10  475.269989  2225.000000  3440.600098  18443.439453
1994-01-11  474.130005  2228.100098  3413.800049  18485.250000
1994-01-12  474.170013  2182.060059  3372.000000  18793.880859
1994-01-13  472.470001  2142.370117  3360.000000  18577.259766

[5 rows x 24 columns]

In [ ]:
df_comp = df_comp.iloc[1:] # Removing the first elements, since we always start 1 period before the first, due to time zone differences of closing prices
del df_comp['^N225']  # Removing the original tickers of the data set
del df_comp['^GSPC']
del df_comp['^GDAXI']
del df_comp['^FTSE']
df_comp=df_comp.asfreq('b') # Setting the frequency of the data
df_comp=df_comp.fillna(method='ffill') # Filling any missing values

Ticker             spx          dax         ftse        nikkei
Price
Date
1994-01-10  475.269989  2225.000000  3440.600098  18443.439453
1994-01-11  474.130005  2228.100098  3413.800049  18485.250000
1994-01-12  474.170013  2182.060059  3372.000000  18793.880859
1994-01-13  472.470001  2142.370117  3360.000000  18577.259766
1994-01-14  474.910004  2151.050049  3400.600098  18973.699219

In [13]:
print (df_comp.head()) # Displaying the first 5 elements to make sure the data was scraped correctly
print (df_comp.tail()) # Making sure the last day we're including in the series are correct

Ticker             spx          dax         ftse        nikkei
Price
Date
1994-01-10  475.269989  2225.000000  3440.600098  18443.439453
1994-01-11  474.130005  2228.100098  3413.800049  18485.250000
1994-01-12  474.170013  2182.060059  3372.000000  18793.880859
1994-01-13  472.470001  2142.370117  3360.000000  18577.259766
1994-01-14  474.910004  2151.050049  3400.600098  18973.699219
Ticker              spx           dax         ftse        nikkei
Price
Date
2019-09-20  2992.070068  12468.009766  7344.899902  22079.089844
2019-09-23  2991.780029  12342.330078  7326.100098  22079.089844
2019-09-24  2966.600098  12307.150391  7291.399902  22098.839844
2019-09-25  2984.870117  12234.179688  7290.000000  22020.150391
2019-09-26  2977.620117  12288.540039  7351.100098  22048.240234